### ISSUE TITLE
New code dump

### ISSUE THREAD

**Issue by goldenjatt** [Hannan-404/FILE#6]
bro file dump krne k bad 1000926978 k bad new code ni araha se set krdein

**Comment by Hannan-404** [comment]
asa.kese hoskta

**Comment by goldenjatt** [comment]
Ho raha hai new new ids nhi aarhi dump krny k bad kal say jis waja say file nhi bn rahi sahi

**Comment by goldenjatt** [comment]
![Screenshot_20230507-214817](https://user-images.githubusercontent.com/132660387/236690817-c673abca-5a07-441c-a2a8-0a7f075b07e5.png)
Ye dekhain 10 bar kr li hai lakin 1st id ye hi hai new code nhi aarha jb k code to 10009272 tk gya hai i think

**Comment by royal009** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/FILE/FILE.py", line 12, in <module>
    import FILE64
ImportError: dlopen failed: "/data/data/com.termux/files/home/FILE/FILE64.so" has unexpected e_machine: 183
pc ma ya masla a raha ha

**Comment by royal009** [comment]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/FILE/FILE.py", line 12, in <module>
    import FILE64
ImportError: dlopen failed: "/data/data/com.termux/files/home/FILE/FILE64.so" has unexpected e_machine: 183
pc ma ya masla a raha ha

**Comment by royal009** [comment]
![Screenshot_2023 10 15_13 43 47 507](https://github.com/Hannan-404/FILE/assets/148011721/861d7f64-0455-46aa-89c6-e30e094cc1d0)

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/FILE/FILE.py", line 12, in <module>
    import FILE64
ImportError: dlopen failed: "/data/data/com.termux/files/home/FILE/FILE64.so" has unexpected e_machine: 183

**Comment by paiwasttaqana** [comment]
Set the settings please
